### ISSUE TITLE
count(NULL)

### ISSUE THREAD

**Issue by xenomporio** [xenomporio-org/Xenomporio#8]
if (!is_null()) {
...
}

**Comment by AlexLedis** [comment]
`(?<![A-Za-z_0-9]{1})(count[ ]*\(([ ]*[$][a-zA-Z]*(?R)?.*)\))`

**Comment by xenomporio** [comment]
`(?<![A-Za-z_0-9]{1}|[?][\s]|[?])(count[ ]*\([\s]*[$](?:[^)(]+|(?R))*+\))`

**Comment by xenomporio** [comment]
sed -i 'LINENRs/count(PARAMETERS)/(!empty(PARAMETERS)?count(PARAMETERS):0)/' FILE

**Comment by xenomporio** [comment]
b974f1c38e559934402c9857d1dc5ff374be93bb
eaa3b1da756dfbc3f0e5097e02b566da9ab35555
